###################
# BUILD FOR LOCAL DEVELOPMENT
###################

FROM node:22.9.0-alpine3.20 AS development

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . .

USER node

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "start:debug"]