services:
  app:
    container_name: api-integration
    build:
      context: .
      dockerfile: Dockerfile.dev
    # image: brunohsweber/comercialweber-api-integration:1.0.0-beta.35
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229" # debug
    env_file:
      - .env
    # depends_on:
    #   - rabbitmq
    restart:
      unless-stopped
    network_mode: "host"
    volumes:
      - .:/usr/src/app

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"     # Porta padrão para conexões AMQP
  #     - "15672:15672"   # Porta para o painel de administração
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest  # Altere para seu usuário
  #     RABBITMQ_DEFAULT_PASS: guest    # Altere para sua senha
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq  # Volume para persistência de dados
  #   restart: 
  #     unless-stopped

volumes:
  rabbitmq_data:
    driver: local