name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
      - alpha

jobs:
  check-application:
    name: Check application
    runs-on: ubuntu-latest
    outputs:
      repo_name: ${{ steps.get_repo_name.outputs.repo_name }}
    steps:
      - name: Start CI Pipeline
        id: get_repo_name
        run: |
          repo_name=$(echo "${{ github.repository }}" | sed 's/\//-/g')
          echo "repo_name=$repo_name" >> $GITHUB_OUTPUT
          echo "Starting CI pipeline for $repo_name repository"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

  # release-version:
  #   name: Release Version
  #   runs-on: ubuntu-latest
  #   needs: [check-application]
  #   outputs:
  #     new_release_version: ${{ steps.release.outputs.new_release_version }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false

  #     - name: Semantic Release
  #       id: release
  #       uses: cycjimmy/semantic-release-action@v4
  #       with:
  #         semantic_version: 21.1.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-version:
    name: Release version
    needs: [check-application]
    uses: comercialweber/github-workflows/.github/workflows/release-version.yaml@main
    secrets: inherit

  # build-and-publish-image:
  #   name: Build and publish image
  #   runs-on: ubuntu-latest
  #   needs: [check-application, release-version]
  #   steps:
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ needs.check-application.outputs.repo_name }}:${{ needs.release-version.outputs.new_release_version }}

  build-and-publish-image:
    name: Build and publish image
    needs: [check-application, release-version]
    uses: comercialweber/github-workflows/.github/workflows/build-and-publish-image.yaml@main
    with:
      repo_name: ${{ needs.check-application.outputs.repo_name }}
      image_tag: ${{ needs.release-version.outputs.new_release_version }}
    secrets: inherit

  vulnerabilities-scan:
    name: Vulnerabilities scan
    needs: [check-application, release-version, build-and-publish-image]
    uses: comercialweber/github-workflows/.github/workflows/vulnerabilities-scan.yaml@main
    with:
      docker_image: ${{ needs.check-application.outputs.repo_name }}:${{ needs.release-version.outputs.new_release_version }}
    secrets: inherit
